# Generated by Django 5.2.4 on 2025-08-02 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_service_alter_reservation_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='profile_image',
            field=models.ImageField(blank=True, help_text='Image de profil (recommandé pour les coiffeuses)', null=True, upload_to='profile_images/'),
        ),
    ]
