# Generated by Django 5.2.4 on 2025-08-03 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0003_userprofile_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='payment_method',
            field=models.CharField(choices=[('mobile', 'Mobile Money'), ('cash', 'Espèces'), ('not_set', 'Non défini')], default='not_set', max_length=20),
        ),
    ]
