# Generated by Django 5.2.4 on 2025-08-03 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0004_reservation_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(choices=[('admin', 'Admin'), ('coiffeuse', 'Esthéticienne'), ('client', 'Client')], max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_image',
            field=models.ImageField(blank=True, help_text='Image de profil (recommandé pour les esthéticiennes)', null=True, upload_to='profile_images/'),
        ),
    ]
