# Generated by Django 5.2.4 on 2025-08-04 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0005_alter_role_name_alter_userprofile_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='justification_annulation',
            field=models.TextField(blank=True, help_text="Justification de l'annulation par le client", null=True),
        ),
    ]
