# Generated by Django 6.0.5 on 2026-05-16 10:32

from django.db import migrations, models


def delete_cancelled_reservations(apps, schema_editor):
    Reservation = apps.get_model('manager', 'Reservation')
    Reservation.objects.filter(statut='annulé').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0007_seed_default_roles'),
    ]

    operations = [
        migrations.RunPython(delete_cancelled_reservations, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='reservation',
            name='statut',
            field=models.CharField(
                choices=[
                    ('en_attente', 'En attente'),
                    ('confirmé', 'Confirmé'),
                    ('payé', 'Payé'),
                    ('terminé', 'Terminé'),
                ],
                default='en_attente',
                max_length=20,
            ),
        ),
    ]
